/**
 * geminiClient.js
 * ───────────────
 * Raw-fetch Gemini REST client with automatic multi-model fallback.
 * Uses ?key= query-param authentication — correct for AQ. format API keys
 * generated by Google AI Studio.
 */

const GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta/models";

// Fallback models in priority order (high quota & fast response)
const FALLBACK_MODELS = [
  "gemini-3.5-flash-lite",
  "gemini-3.1-flash-lite",
  "gemini-3.5-flash",
  "gemini-3.6-flash",
];

/**
 * Execute a single generateContent call to a specific model.
 */
async function callSingleModel({ model, contents, systemInstruction, tools }) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY is not configured.");

  const url = `${GEMINI_BASE}/${model}:generateContent?key=${encodeURIComponent(apiKey)}`;
  const body = { contents };

  if (systemInstruction) {
    body.system_instruction = { parts: [{ text: systemInstruction }] };
  }

  if (tools && tools.length > 0) {
    body.tools = [{ functionDeclarations: tools }];
  }

  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(60000),
  });

  const data = await response.json();

  if (!response.ok || data.error) {
    const status = response.status;
    const msg = data.error?.message || `HTTP ${status}`;
    const err = new Error(msg);
    err.status = status;
    err.code = data.error?.code || status;
    throw err;
  }

  return data;
}

/**
 * Call Gemini generateContent via REST API with automated model fallback.
 * Supports function calling, system instructions, and multi-turn history.
 *
 * @param {Object} opts
 * @param {string}  [opts.model]             - Preferred model name
 * @param {Array}    opts.contents          - Conversation contents array
 * @param {string}  [opts.systemInstruction] - System prompt text
 * @param {Array}   [opts.tools]            - Gemini function declarations array
 * @returns {Promise<Object>}               - Raw Gemini API response
 */
async function generateContent({ model, contents, systemInstruction, tools }) {
  const primaryModel = model || process.env.GEMINI_MODEL || "gemini-3.5-flash-lite";

  // Build candidate model list with primary first, followed by unique fallbacks
  const candidateModels = [
    primaryModel,
    ...FALLBACK_MODELS.filter((m) => m !== primaryModel),
  ];

  let lastError = null;

  for (let i = 0; i < candidateModels.length; i++) {
    const currentModel = candidateModels[i];
    try {
      return await callSingleModel({
        model: currentModel,
        contents,
        systemInstruction,
        tools,
      });
    } catch (err) {
      lastError = err;
      const isQuotaOrAvailability =
        err.status === 429 ||
        err.status === 503 ||
        err.status === 404 ||
        err.message?.includes("quota") ||
        err.message?.includes("RESOURCE_EXHAUSTED") ||
        err.message?.includes("high demand") ||
        err.message?.includes("no longer available");

      if (isQuotaOrAvailability && i < candidateModels.length - 1) {
        const nextModel = candidateModels[i + 1];
        console.warn(
          `⚠️ [Gemini] Model ${currentModel} returned ${err.status || "error"} (${err.message.slice(0, 60)}...). Switching to fallback model: ${nextModel}`
        );
        continue;
      }

      throw err;
    }
  }

  throw lastError || new Error("Failed to generate content from available Gemini models.");
}

/**
 * Simple single-turn text generation helper (for report card remarks, etc.)
 *
 * @param {string} prompt
 * @param {string} [model]
 * @returns {Promise<string>} - Generated text
 */
async function generateText(prompt, model) {
  const data = await generateContent({
    model,
    contents: [{ role: "user", parts: [{ text: prompt }] }],
  });

  return data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "";
}

/**
 * Extract text and function calls from a Gemini response candidate.
 *
 * @param {Object} data - Raw Gemini API response
 * @returns {{ text: string, functionCalls: Array, parts: Array }}
 */
function parseResponse(data) {
  const parts = data.candidates?.[0]?.content?.parts || [];
  const text = parts
    .filter((p) => p.text)
    .map((p) => p.text)
    .join("")
    .trim();
  const functionCalls = parts.filter((p) => p.functionCall);
  return { text, functionCalls, parts };
}

module.exports = { generateContent, generateText, parseResponse };
