/**
 * geminiClient.js
 * ───────────────
 * Raw-fetch Gemini REST client.
 * Uses ?key= query-param authentication — correct for AQ. format API keys
 * generated by Google AI Studio.
 */

const GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta/models";

/**
 * Call Gemini generateContent via REST API.
 * Supports function calling, system instructions, and multi-turn history.
 *
 * @param {Object} opts
 * @param {string}   opts.model            - Model name e.g. "gemini-3.6-flash"
 * @param {Array}    opts.contents         - Conversation contents array
 * @param {string}  [opts.systemInstruction] - System prompt text
 * @param {Array}   [opts.tools]           - Gemini function declarations array
 * @returns {Promise<Object>}              - Raw Gemini API response
 */
async function generateContent({ model, contents, systemInstruction, tools }) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY is not configured.");

  const targetModel = model || process.env.GEMINI_MODEL || "gemini-3.6-flash";
  const url = `${GEMINI_BASE}/${targetModel}:generateContent?key=${encodeURIComponent(apiKey)}`;

  const body = { contents };

  if (systemInstruction) {
    body.system_instruction = { parts: [{ text: systemInstruction }] };
  }

  if (tools && tools.length > 0) {
    body.tools = [{ functionDeclarations: tools }];
  }

  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(90000),
  });

  const data = await response.json();

  if (!response.ok || data.error) {
    const msg = data.error?.message || `HTTP ${response.status}`;
    throw new Error(`Gemini API error: ${msg}`);
  }

  return data;
}

/**
 * Simple single-turn text generation helper (for remarks etc.)
 *
 * @param {string} prompt
 * @param {string} [model]
 * @returns {Promise<string>} - Generated text
 */
async function generateText(prompt, model) {
  const modelName = model || process.env.GEMINI_MODEL || "gemini-3.6-flash";
  const data = await generateContent({
    model: modelName,
    contents: [{ role: "user", parts: [{ text: prompt }] }],
  });

  return data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "";
}

/**
 * Extract text and function calls from a Gemini response candidate.
 *
 * @param {Object} data - Raw Gemini API response
 * @returns {{ text: string, functionCalls: Array, parts: Array }}
 */
function parseResponse(data) {
  const parts = data.candidates?.[0]?.content?.parts || [];
  const text = parts
    .filter((p) => p.text)
    .map((p) => p.text)
    .join("")
    .trim();
  const functionCalls = parts.filter((p) => p.functionCall);
  return { text, functionCalls, parts };
}

module.exports = { generateContent, generateText, parseResponse };
